source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, '14.0'

target 'Taxi' do
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
end
